OJewelry/Models/MetalCode.cs
namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class MetalCode
    {
        public int Id { get; set; }

        public int? CompanyId { get; set; }

        [StringLength(6)]
        public string Code { get; set; }

        [StringLength(50)]
        public string Desc { get; set; }

        [Required]
        public decimal Market { get; set; }

        [Required]
        public float Multiplier { get; set; }

        public virtual Company Company { get; set; }
    }
}

OJewelry/Controllers/MetalCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OJewelry.Models;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using OJewelry.Classes;
using System.IO;

namespace OJewelry.Controllers
{
    [Authorize]
    public class MetalCodesController : Controller
    {
        private OJewelryDB db = new OJewelryDB();

        // GET: MetalCodes
        public ActionResult Index(int? companyId)
        {
            if (companyId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            companyId = companyId.Value;
            ViewBag.CompanyId = companyId;
            ViewBag.CompanyName = db._Companies.Find(companyId)?.Name;

            return View(db.MetalCodes.Where(mc => mc.CompanyId == companyId).OrderBy(mc=>mc.Code).ToList());
        }

        // GET: MetalCodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MetalCode metalCode = db.MetalCodes.Find(id);
            if (metalCode == null)
            {
                return HttpNotFound();
            }
            return View(metalCode);
        }

        // GET: MetalCodes/Create
        public ActionResult Create(int companyId)
        {
            ViewBag.CompanyId = companyId;
            ViewBag.CompanyName = db._Companies.Find(companyId)?.Name;

            return View();
        }

        // POST: MetalCodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Code,Desc,Market,Multiplier,CompanyId")] MetalCode metalCode)
        {
            if (ModelState.IsValid)
            {
                db.MetalCodes.Add(metalCode);
                db.SaveChanges();
                return RedirectToAction("Index", new { metalCode.CompanyId });
            }
            ViewBag.CompanyId = metalCode.CompanyId;
            ViewBag.CompanyName = db._Companies.Find(metalCode.CompanyId)?.Name;

            return View(metalCode);
        }

        // GET: MetalCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MetalCode metalCode = db.MetalCodes.Find(id);
            if (metalCode == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = metalCode.CompanyId;
            ViewBag.CompanyName = db._Companies.Find(metalCode.CompanyId)?.Name;
            return View(metalCode);
        }

        // POST: MetalCodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Desc,Market,Multiplier,CompanyId")] MetalCode metalCode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(metalCode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { metalCode.CompanyId });
            }
            ViewBag.CompanyId = metalCode.CompanyId;
            ViewBag.CompanyName = db._Companies.Find(metalCode.CompanyId)?.Name;
            return View(metalCode);
        }

        // GET: MetalCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeleteMetalCodeModel dmcm = new DeleteMetalCodeModel()
            {
                item = db.MetalCodes.Find(id)
            };
            if (dmcm.item == null)
            {
                return HttpNotFound();
            }
            if (db.Castings.Where(s => s.MetalCodeID == id).Count() != 0)
            {
                // List the styles
                List<Style> styles = new List<Style>();
                styles = db.StyleCastings.Where(sc => sc.Casting.MetalCodeID == id).Select(sc => sc.Style).ToList();
                dmcm.styles = styles.Distinct(new StyleEqualityComparer()).ToList();
                dmcm.bError = true;
            }
            return View(dmcm);
        }

        // POST: MetalCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MetalCode metalCode = db.MetalCodes.Find(id);

            int companyId = metalCode.CompanyId.Value;
            db.MetalCodes.Remove(metalCode);
            db.SaveChanges();
            return RedirectToAction("Index", new { companyId });
        }

        public FileResult ExportMetalsReport(int companyId, string sCurrDate)
        {
            byte[] b;

            DateTime curr;
            sCurrDate = sCurrDate.Replace("'", "");
            if (!DateTime.TryParse(sCurrDate, out curr))
            {
                curr = DateTime.Now.ToLocalTime();
            }
            string currDate = $"{curr.ToShortDateString()} {curr.ToShortTimeString()}";

            DCTSOpenXML oxl = new DCTSOpenXML();
            using (MemoryStream memStream = new MemoryStream())
            {
                using (SpreadsheetDocument document = SpreadsheetDocument.Create(memStream, SpreadsheetDocumentType.Workbook))
                {

                    // Build Excel File
                    WorkbookPart workbookPart = document.AddWorkbookPart();
                    workbookPart.Workbook = new Workbook();

                    WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                    worksheetPart.Worksheet = new Worksheet(new SheetData());

                    Sheets sheets = document.WorkbookPart.Workbook.AppendChild(new DocumentFormat.OpenXml.Spreadsheet.Sheets());

                    // declare locals
                    Row row;
                    Cell cell;
                    string loc;
                    int rr;
                    // Build sheet
                    Sheet sheet = new Sheet()
                    {
                        Id = workbookPart.GetIdOfPart(worksheetPart),
                        SheetId = 1,
                        Name = "Metals"
                    };
                    sheets.Append(sheet);

                    Worksheet worksheet = new Worksheet();
                    SheetData sd = new SheetData();
                    // Title
                    row = new Row();
                    cell = oxl.SetCellVal("A1", $"Export - Metal Codes  {currDate}");
                    row.Append(cell);
                    sd.Append(row);
                    row = new Row();
                    cell = oxl.SetCellVal("A2", "");
                    row.Append(cell);
                    sd.Append(row);

                    // Headers
                    row = new Row();
                    oxl.columns.Append(new Column() { Width = oxl.ComputeExcelCellWidth(oxl.minWidth), Min = 1, Max = 1, BestFit = true, CustomWidth = true }); cell = oxl.SetCellVal("A3", "Code"); row.Append(cell);
                    oxl.columns.Append(new Column() { Width = oxl.ComputeExcelCellWidth(oxl.minWidth), Min = 2, Max = 2, BestFit = true, CustomWidth = true }); cell = oxl.SetCellVal("B3", "Desc"); row.Append(cell);
                    oxl.columns.Append(new Column() { Width = oxl.ComputeExcelCellWidth(oxl.minWidth), Min = 3, Max = 3, BestFit = true, CustomWidth = true }); cell = oxl.SetCellVal("C3", "Market"); row.Append(cell);
                    oxl.columns.Append(new Column() { Width = oxl.ComputeExcelCellWidth(oxl.minWidth), Min = 4, Max = 4, BestFit = true, CustomWidth = true }); cell = oxl.SetCellVal("D3", "Multiplier"); row.Append(cell);
                    worksheet.Append(oxl.columns);
                    sd.Append(row);
                    List<MetalCode> Metals = db.MetalCodes.Where(m => m.CompanyId == companyId).OrderBy(m => m.Code).ToList();
                    // Content
                    for (int i = 0; i < Metals.Count(); i++)
                    {
                        row = new Row();
                        rr = 4 + i;
                        loc = "A" + rr; cell = oxl.SetCellVal(loc, Metals[i].Code); row.Append(cell);
                        loc = "B" + rr; cell = oxl.SetCellVal(loc, Metals[i].Desc); row.Append(cell);
                        loc = "C" + rr; cell = oxl.SetCellVal(loc, Metals[i].Market); row.Append(cell);
                        loc = "D" + rr; cell = oxl.SetCellVal(loc, Metals[i].Multiplier); row.Append(cell);
                        sd.Append(row);
                    }
                    worksheet.Append(sd);
                    // Autofit columns - ss:AutoFitWidth="1"
                    worksheetPart.Worksheet = worksheet;
                    workbookPart.Workbook.Save();
                    document.Close();

                    b = memStream.ToArray();
                    return File(b, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "Metals as of " + $"{currDate}" + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OJewelry/Views/MetalCodes/Create.cshtml
@model OJewelry.Models.MetalCode

@{
    ViewBag.Title = $"{ViewBag.CompanyName} - Create Metal Code";
}

<h2>Create a Metal Code for <i>@ViewBag.CompanyName</i></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Metal Code</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Market, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Market, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Market, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multiplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Multiplier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Multiplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Cancel", "Index", "Findings", new { companyId = (int)ViewBag.CompanyId }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", (int) ViewBag.CompanyId)
</p>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OJewelry/Views/MetalCodes/Delete.cshtml
@model OJewelry.Models.DeleteMetalCodeModel

@{
    ViewBag.Title = $"{Model.item.Code} - Delete";
}

<h2>Delete the <i>@Model.item.Code</i> Metal Code?</h2>

@if (Model.bError)
{
<div class="largeError">
    <p>Error - The '@Model.item.Code' Metal Code is use in the following style(s)</p>
    <ul>
        @foreach (OJewelry.Models.Style sty in Model.styles)
        {
            <li class="text-danger bold"><i>@sty.StyleName</i></li>
        }
    </ul>
    <br />
    @Html.ActionLink("Cancel", "Index", "MetalCodes", new { companyId = Model.item.CompanyId }, new { @class = "btn btn-default" })
</div>
}
else
{
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Metal Code</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.item.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.item.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.item.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.item.Desc)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div>
            @Html.ValidationSummary(null, new { @class = "text-danger" })
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Cancel", "Index", "MetalCodes", new { companyId = Model.item.CompanyId }, new { @class = "btn btn-default" })
        </div>
    }
</div>
}
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", Model.item.CompanyId)
</p>

OJewelry/Views/MetalCodes/Details.cshtml
@model OJewelry.Models.MetalCode

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Metal Code</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OJewelry/Views/MetalCodes/Edit.cshtml
@model OJewelry.Models.MetalCode

@{
    ViewBag.Title = $"{Model.Code} - Edit Metal Code";
}

<h2>Edit the <i>@Model.Code</i> Metal Code</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Metal Code</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CompanyId)

    <div class="form-group">
        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Market, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Market, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Market, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Multiplier, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Multiplier, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Multiplier, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-default" })
            @Html.ActionLink("Cancel", "Index", "MetalCodes", new { companyId = Model.CompanyId }, new { @class = "btn btn-default" })
        </div>
    </div>
</div>
}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", Model.CompanyId)
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OJewelry/Views/MetalCodes/Index.cshtml
@model IEnumerable<OJewelry.Models.MetalCode>

@{
    ViewBag.Title = "Labor Table";
}

<h2>Metal Codes for <i>@ViewBag.CompanyName</i></h2>

<p>
    @Html.ActionLink("Create New Metal Code", "Create", new { @companyId = ViewBag.companyId })
</p>
@{
    string jsCall = $"GetLocalTime({ViewBag.companyId}, '{Url.Action("ExportMetalsReport")}')";
}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", (int)ViewBag.companyId) |
    <a class="ExportLink" href="#" onclick="@jsCall">Export Metal Codes to Excel</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Market)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Multiplier)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Market)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Multiplier)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", (int)ViewBag.companyId) |
    <a class="ExportLink" href="#" onclick="@jsCall">Export Metal Codes to Excel</a>
</p>

@section Scripts {
    @Scripts.Render("~/Scripts/GetLocalTime.js")
}