OJewelry/Models/Memo.cs
namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Memo")]
    public partial class Memo
    {
        public int Id { get; set; }

        public int PresenterID { get; set; }

        public int? StyleID { get; set; }

        public DateTime? Date { get; set; }

        public double Quantity { get; set; }

        [StringLength(255)]
        public string Notes { get; set; }

        public virtual Presenter Presenter { get; set; }

        public virtual Style Style { get; set; }
    }
}

OJewelry/Models/MemoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace OJewelry.Models
{
    /*
     public class PresenterModelx
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public String Phone { get; set; }
        public String Email { get; set; }
    }
    */
    public class MemoModel
    {
        public int Id { get; set; }
        public String PresenterName  { get; set; }
        public String PresenterPhone { get; set; }
        public String PresenterEmail { get; set; }
        public DateTime? date { get; set; }
        public double Quantity { get; set; }
        public String Notes { get; set; }
        [Display(Name = "Return Qty")] public int ReturnQty { get; set; }

    }

    public class MemoViewModel
    {
        public StyleModel style { get; set; }
        public List<MemoModel> Memos { get; set; }
        public int SendReturnMemoRadio { get; set; } // Radio Bth
        public int NewExistingPresenterRadio { get; set; } // Radio Bth
        [Display(Name = "Locations")]
        public List<SelectListItem> Presenters { get; set; } // dropdown

        [Display(Name="Name")]
        [Required(ErrorMessage = "Name is required.")]
        public String PresenterName { get; set; }

        [Display(Name = "Location Phone")]
        [Required(ErrorMessage = "Phone is required.")]
        [DataType(DataType.PhoneNumber)]
        [Phone]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public String PresenterPhone { get; set; }

        [Display(Name = "Location Email")]
        [Required(ErrorMessage = "Email is required.")]
        [DataType(DataType.EmailAddress)]
        public String PresenterEmail { get; set; }

        [Display(Name = "Send Qty")]
        public int SendQty { get; set; }
        public int PresenterId { get; set; }
        public int numPresentersWithStyle { get; set; }
        public int CompanyId { get; set; }
    }
    
    public class MemoViewModelBinder : DefaultModelBinder
    {
        public override object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            MemoViewModel m = (MemoViewModel)base.BindModel(controllerContext, bindingContext);
            var request = controllerContext.HttpContext.Request;
            // build memos
            m.Memos = new List<MemoModel>();
            for (int i = 0; i <m.numPresentersWithStyle; i++)
            {
                StringBuilder sb = new StringBuilder();
                sb.AppendFormat("Memos[{0}].ReturnQty", i);
                string s = request.Form.Get(sb.ToString());
                if (!Int32.TryParse(s, out int returnQty)) returnQty = 0;
                sb.Clear();
                sb.AppendFormat("Memos[{0}].Id", i);
                s = request.Form.Get(sb.ToString());
                if (!Int32.TryParse(s, out int id)) id = 0;
                sb.Clear();
                sb.AppendFormat("Memos[{0}].Quantity", i);
                s = request.Form.Get(sb.ToString());
                if (!Int32.TryParse(s, out int qty)) qty = 0;

                MemoModel memo = new MemoModel()
                {
                    Id = id,
                    ReturnQty = returnQty,
                    Quantity = qty,
                };
                m.Memos.Add(memo);
            }

            return m;           
            
        }
    }
}

OJewelry/Controllers/StylesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Diagnostics.SymbolStore;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Microsoft.WindowsAzure.Storage.Blob;
using OJewelry.Classes;
using OJewelry.Models;

namespace OJewelry.Controllers
{
    [Authorize]
    public class StylesController : Controller
    {
        private OJewelryDB db = new OJewelryDB();

        // GET: Styles
        public ActionResult Index(int? CollectionId)
        {
            var styles = db.Styles.Include(s => s.Collection).Where(i => i.CollectionId == CollectionId).OrderBy(s => s.StyleName).Include(s => s.JewelryType);
            ViewBag.CollectionName = db.Collections.Find(CollectionId).Name;
            ViewBag.CollectionId = CollectionId;
            ViewBag.CompanyId = db.Collections.Find(CollectionId).CompanyId;
            return View(styles.ToList());
        }

        // GET: Styles/Details/5
        public ActionResult Details(int? id)
        {
            StyleViewModel svm = new StyleViewModel();
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            svm.Style = db.Styles.Find(id);
            if (svm.Style == null)
            {
                return HttpNotFound();
            }
            svm.Populate(id, db);
            return View(svm);
        }

        // GET: Styles/Create
        public ActionResult Create(int collectionId)
        {
            Collection co = db.Collections.Find(collectionId);
            StyleViewModel svm = new StyleViewModel();
            svm.CompanyId = co.CompanyId;
            svm.SVMOp = SVMOperation.Create;
            svm.Populate(null, db);
            AddDefaultEntries(svm);
            return CreateNew(svm.CompanyId, collectionId, svm);
        }

        public ActionResult CreateNew(int companyId, int collectionId, StyleViewModel svm)
        {
            svm.Style.Collection = db.Collections.Find(collectionId);
            svm.Style.CollectionId = collectionId;
            svm.CompanyId = svm.Style.Collection.CompanyId;

            svm.PopulateDropDownData(db);
            svm.PopulateDropDowns(db);
            svm.RepopulateComponents(db); // iterate thru the data and repopulate the links

            ViewBag.CollectionId = new SelectList(db.Collections.Where(x => x.CompanyId == svm.CompanyId), "Id", "Name", svm.Style.CollectionId);
            //ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes.Where(x => x.CompanyId == companyId), "Id", "Name", svm.Style.JewelryTypeId);
            ViewBag.MetalWtUnitId = new SelectList(db.MetalWeightUnits.OrderBy(mwu => mwu.Unit), "Id", "Unit", svm.Style.MetalWtUnitId);
            return View("Create", svm);
        }

        public void AddDefaultEntries(StyleViewModel svm)
        {
            // Get the cost data and find initial values for the Finishing Labor & Packaging Costs. Both are based on the style's jewelry type
            decimal flPrice = 0;
            decimal packPrice = 0;

            JewelryType jt = db.JewelryTypes.Where(j => svm.CompanyId == j.CompanyId).FirstOrDefault();
            if (jt != null)
            {
                flPrice = jt.FinishingCost;
                packPrice = jt.PackagingCost;
            }

            // Add 2 Fixed Labor entries and 1 Fixed Misc entry
            LaborComponent lc = new LaborComponent
            {
                Id = -1,
                Name = StyleViewModel.FinishingLaborName,
                State = LMState.Fixed,
                PPP = flPrice,
                Qty = 1,
                Total = flPrice
            };
            svm.Labors.Add(lc);
            MiscComponent mc = new MiscComponent
            {
                Id = -1,
                Name = StyleViewModel.PackagingName,
                State = SVMStateEnum.Fixed,
                PPP = packPrice,
                Qty = 1,
                Total = packPrice
            };
            svm.Miscs.Add(mc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Copy(StyleViewModel svm)
        {
            ModelState.Clear();
            svm.SVMOp = SVMOperation.Create;
            StyleViewModel newsvm = new StyleViewModel(svm, db);
            await SaveImageInStorage(db, newsvm, true);

            newsvm.Style.Collection = db.Collections.Find(newsvm.Style.CollectionId);
            newsvm.CompanyId = newsvm.Style.Collection.CompanyId;
            newsvm.CopiedStyleName = svm.Style.StyleName;

            newsvm.PopulateDropDownData(db);
            newsvm.PopulateDropDowns(db);
            newsvm.LookupComponents(db); // iterate thru the data and repopulate the data

            ViewBag.CollectionId = new SelectList(db.Collections.Where(x => x.CompanyId == newsvm.CompanyId), "Id", "Name", newsvm.Style.CollectionId);
            //ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes.Where(x => x.CompanyId == newsvm.CompanyId), "Id", "Name", newsvm.Style.JewelryTypeId);
            ViewBag.MetalWtUnitId = new SelectList(db.MetalWeightUnits.OrderBy(mwu => mwu.Unit), "Id", "Unit", newsvm.Style.MetalWtUnitId);
            return View(newsvm);
        }

        private bool CheckForNameAndNumberUniqueness(StyleViewModel svm)
        {
            // make sure the collection is valid
            if (svm.Style.Collection == null)
            {
                svm.Style.Collection = db.Collections.Find(svm.Style.CollectionId);
            }
            int iStyleNames = db.Styles.
                Join(db.Collections, s => s.CollectionId, col => col.Id, (s, c) => new
                {
                    StyleId = s.Id,
                    //StyleNum = s.StyleNum,
                    StyleName = s.StyleName,
                    CompanyId = c.CompanyId,
                }).Where(x => x.CompanyId == svm.CompanyId
                    && x.StyleId != svm.Style.Id
                    && (x.StyleName == svm.Style.StyleName)).Count();
            if (iStyleNames != 0)
            {
                ModelState.AddModelError("Style.StyleName", "Style with this name already exists for " + db.FindCompany(svm.CompanyId).Name + ".");
            }

            if (iStyleNames != 0)
            {
                return false;
            }
            return true;
        }

        // POST: Styles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name,StyleNum,StyleName,Desc,JewelryTypeId,CollectionId,IntroDate,Image,Width,Length,ChainLength,RetailRatio,RedlineRatio,Quantity")] Style style)
        public async Task<ActionResult> Create(StyleViewModel svm)
        {
            svm.SVMOp = SVMOperation.Create;
            bool b = CheckForNameAndNumberUniqueness(svm);
            // Check special cases in Model
            CheckModelState(svm);
            TraceModelStateErrors(svm.Style.StyleName);
            
            if (b) // is there a style with the same number for this company?
            {
                // No, add it
                svm.SVMState = SVMStateEnum.Added;
            }
            return await Edit(svm);
        }

        // GET: Styles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            StyleViewModel svm = new StyleViewModel();
            svm.Style = db.Styles.Find(id);
            if (svm.Style == null)
            {
                return HttpNotFound();
            }
            svm.Style.JewelryType = db.JewelryTypes.Find(svm.Style.JewelryTypeId);
            Collection co = db.Collections.Find(svm.Style.CollectionId);
            svm.CompanyId = co.CompanyId;
            svm.Style.MetalWeightUnit = new MetalWeightUnit
            {
                Unit = "DWT"
            };
            svm.Populate(id, db);
            string markup = db.FindCompany(svm.CompanyId).markup;
            if (markup == null) markup = "[]";
            svm.markups = JsonConvert.DeserializeObject<List<Markup>>(markup);
            ViewBag.CollectionId = new SelectList(db.Collections.Where(x => x.CompanyId == co.CompanyId), "Id", "Name", svm.Style.CollectionId);
            //ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes.Where(x => x.CompanyId == co.CompanyId), "Id", "Name", svm.Style.JewelryTypeId);
            ViewBag.MetalWtUnitId = new SelectList(db.MetalWeightUnits.OrderBy(mwu => mwu.Unit), "Id", "Unit", svm.Style.MetalWtUnitId);
            return View(svm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(StyleViewModel svm)
        {
            CheckForNameAndNumberUniqueness(svm);
            int i;
            // Check special cases in Model
            CheckModelState(svm);
            // 
            TraceModelStateErrors(svm.Style.StyleName);
            // Save the Style and all edited components; add the new ones and remove the deleted ones
            if (ModelState.IsValid)
            {
                bool bUseLaborTable = svm.Style.JewelryType.bUseLaborTable;
                svm.Style.JewelryType = null; // hack to avoid maismatch of JewelryTypeId error!!!

                if (db.Entry(svm.Style).State != EntityState.Added) db.Entry(svm.Style).State = EntityState.Modified;
                // Iterate thru the components
                // Castings
                if (svm.Castings != null)
                {
                    i = -1;

OJewelry/Views/Styles/Copy.cshtml
@model OJewelry.Models.StyleViewModel

@{
    ViewBag.Title = $"{Model.CopiedStyleName} - Copy";
}

<h2>Copy of <i>(@Model.CopiedStyleName)</i> style</h2>

@using (Html.BeginForm("Create", "Styles", FormMethod.Post, new { id = "StylesForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="StyleCostSheet form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.Style.CollectionId)
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.CopiedStyleName)

        @Html.Partial("_StyleCreateEditPartial", Model)

        <div>
            @Html.Partial("_CostComponentsPartial", Model)
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default saveBtn" formaction="../Create" />
            </div>                    
            <div class="fauxBtnGroup col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
            </div>
        </div>
    </div>
}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.ActionLink("Style List", "Index", new { CollectionId = @Model.Style.CollectionId }) |
    @Html.Partial("_CompanyNavPartial", Model.CompanyId)
</p>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/Scripts/Style_ComponentMgt.js")
    @Scripts.Render("~/Scripts/CreateEditComponents.js")
}

OJewelry/Views/Styles/Create.cshtml
@model OJewelry.Models.StyleViewModel

@{
    ViewBag.Title = $"{Model.Style.Collection.Name} - Create Style";
}

<h2>Create a Style for the <i>@Model.Style.Collection.Name</i> collection</h2>

@{
    if (Model.drpJewelryTypes.Count() == 0)
    {
        using (Html.BeginForm("CreateOnAddStyle", "JewelryTypes", new { companyId = Model.CompanyId }, FormMethod.Post, null))
        {
            @Html.AntiForgeryToken()
            <p class="text-danger">You must have a Jewelry Type to create a style</p>
            <input type="submit" value="Create" class="btn btn-default" />
            <br />
            <br />
        }
    }
    else
    {
        using (Html.BeginForm("Create", "Styles", FormMethod.Post, new { id = "StylesForm", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="StyleCostSheet form-horizontal">
                <h4>Style</h4>
                <hr />
                @Html.HiddenFor(model => model.Style.CollectionId)
                @Html.HiddenFor(model => model.CompanyId)

                @Html.Partial("_StyleCreateEditPartial", Model)

                <div>
                    @Html.Partial("_CostComponentsPartial", Model)
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Create" class="btn btn-default saveBtn" formaction="Create" />
                    </div>
                    <div class="fauxBtnGroup col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
                    </div>
                </div>
            </div>
        }
    }
}
<br />
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.ActionLink("Style List", "Index", new { CollectionId = @Model.Style.CollectionId }) |
    @Html.Partial("_CompanyNavPartial", Model.CompanyId)
</p>


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/Scripts/Style_ComponentMgt.js")
    @Scripts.Render("~/Scripts/CreateEditComponents.js")
}

OJewelry/Views/Styles/Delete.cshtml
@model OJewelry.Models.StyleViewModel

@{
    ViewBag.Title = $"{Model.Style.StyleName} - Delete";
}

<h2>Delete the <i>@Model.Style.StyleName</i> style</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <div class="row StyleDelete">
        <div class="col-sm-7">
            <dl class="dl-horizontal ">
                <dt>
                    @Html.DisplayNameFor(model => model.Style.StyleName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Style.StyleName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Style.Desc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Style.Desc)
                </dd>

                <dt>
                    @Html.DisplayName("COLLECTION ")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Style.Collection.Name)
                </dd>

                <dt>
                    @Html.DisplayName("JEWELRY TYPE")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Style.JewelryType.Name)
                </dd>
            </dl>
        </div>
        <div class="col-sm-5">
            <div class="StyleDeleteRightHeader">
                @{var imgurl = (Model.Style.Image != null) ? Model.Style.Image : "/Images/logo.png"; }
                <img src="@imgurl" class="StyleImage centerImage" />
            </div>
        </div>
    </div>

    @using (Html.BeginForm("DeleteConfirmed", "Styles", FormMethod.Post, new { id = "StylesDeleteForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Style.Id)
        @Html.HiddenFor(m => m.Style.JewelryTypeId)
        @Html.HiddenFor(m => m.Style.JewelryType.bUseLaborTable)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Cancel", "Index", "Styles", new { CollectionId = Model.Style.CollectionId }, new { @class = "btn btn-default" })


        </div>
        <br />
        <div>
            <p class="MainMenu">
                @Html.ActionLink("Companies", "Index", "Companies") |
                @Html.ActionLink("Style List", "Index", new { CollectionId = @Model.Style.CollectionId }) |
                @Html.Partial("_CompanyNavPartial", Model.Style.Collection.CompanyId)
            </p>
        </div>

    }
</div>

OJewelry/Views/Styles/Edit.cshtml
@model OJewelry.Models.StyleViewModel
@using OJewelry.Models
@{
    ViewBag.Title = $"{Model.Style.StyleName} - Edit";
}

<h2>Edit the <i>@Model.Style.StyleName</i> Cost Sheet</h2>


@using (Html.BeginForm("Edit", "Styles", FormMethod.Post, new { id = "StylesForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="StyleCostSheet form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.Style.Id)
        @Html.HiddenFor(model => model.Style.CollectionId)
        @Html.HiddenFor(model => model.Style.MetalWtUnitId)
        @Html.HiddenFor(model => model.CompanyId)

        @Html.Partial("_StyleCreateEditPartial", Model)

        <div>
            @Html.Partial("_CostComponentsPartial", Model)
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" formaction="~/Styles/Edit" class="btn btn-default saveBtn" />
                <input type="button" value="Print" formaction="~/Styles/Print/@Model.Style.Id" class="btn btn-default saveBtn" formtarget="_blank" />
                <input type="button" value="Copy" formaction="~/Styles/Copy/@Model.Style.Id" class="btn btn-default saveBtn" />
                <input type="button" value="Delete" formaction="~/Styles/Delete" class="btn btn-default saveBtn" />
                <input type="button" value="Pricing" class="btn btn-default pricingBtn trigger_ojPopup" />

                @Html.ActionLink("Mechanical", "Delete", new { id = Model.Style.Id }, new { @class = "btn btn-default hide saveBtn" })
                @Html.ActionLink("Worksheet", "Delete", new { id = Model.Style.Id }, new { @class = "btn btn-default hide saveBtn" })
                @*<a class="">Pricing</a>*@
            </div>
            <div class="fauxBtnGroup fauxhide col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
                <input type="submit" value="Print" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
                <input type="submit" value="Copy" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
                <input type="submit" value="Delete" class="btn btn-default fauxBtn fauxHide" disabled="disabled" />
                <input type="button" value="Pricing" class="btn btn-default trigger_ojPopup fauxBtn fauxHide" disabled="disabled" />

                @Html.ActionLink("Mechanical", "Delete", new { id = Model.Style.Id }, new { @class = "btn btn-default hide fauxHide saveBtn" })
                @Html.ActionLink("Worksheet", "Delete", new { id = Model.Style.Id }, new { @class = "btn btn-default hide fauxHide saveBtn" })
                @*<a class="">Pricing</a>*@
            </div>
        </div>
    </div>
}
    <br />
    <p class="MainMenu">
        @Html.ActionLink("Companies", "Index", "Companies") |
        @Html.ActionLink("Style List", "Index", new { CollectionId = @Model.Style.CollectionId }) |
        @Html.Partial("_CompanyNavPartial", Model.CompanyId)
    </p>

    @*<div>
        <p>----------------------------------------------</p>
        <div>
            <h3>Cost for XYZ</h3>
            <div class="row">
                <div class="col-xs-6 col-sm-6">Cost x 1.6</div>
                <div class="col-xs-6 col-sm-6">: value</div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-sm-6">Cost x 2</div>
                <div class="col-xs-6 col-sm-6">: value</div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-sm-6">Cost x 2.2</div>
                <div class="col-xs-6 col-sm-6">: value</div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-sm-6">Cost x 2.4</div>
                <div class="col-xs-6 col-sm-6">: value</div>
            </div>
        </div>
        <p>----------------------------------------------</p>
    </div>
    *@

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/Scripts/Style_ComponentMgt.js")
    @Scripts.Render("~/Scripts/CreateEditComponents.js")
}

<script>
    function ojPopupDraw() {
        $('.saveBtn').prop('disabled', false);
        const gt = $("#GrandTotal");
        const cn = $("#Style_StyleName").val();
        $(ojPopUpTContent).html(`
            <h3>Cost for <i>${cn}</i>: <b>$${gt.html()}</b></h3>
@if (Model.markups.Count == 0)
{
            <br/>
            <p>No markups defined</p>
} else {
    foreach (Markup m in Model.markups)
    {
            <div class="row">
                <div class="col-xs-6 col-sm-3">@m.title</div>
                <div class="col-xs-6 col-sm-3">: $${ComputeMarkupValue(@m.multiplier, @m.ratio, @m.margin, @m.Addend, gt.html())}</div>
            </div>
    }
}
        </div>
        <br/>
        `);
    }
    function ComputeMarkupValue(multiplier, markup, margin, addend, amt) { // show amt * 2 *  multiplier in cost popup
        var cost;
        if (markup !== 0) {
            cost = (Math.trunc((amt * (1 + multiplier / 100) * (1 + markup / 100) + addend) * 4 )/ 4).toFixed(2);
        } else {
            cost = (Math.trunc((amt * (1 + multiplier / 100) / (1 - margin / 100) + addend) * 4) / 4).toFixed(2);
        }
        return cost;
    }
</script>

OJewelry/Views/Styles/Print.cshtml
@model OJewelry.Models.StyleViewModel

@{
    ViewBag.Title = Model.Style.StyleName + " Cost Sheet";
    Layout = "../Shared/_PrintLayout.cshtml";
}

@using (Html.BeginForm("Edit", "Styles", FormMethod.Post, new {id = "StylePrintForm"}))
{
    <div class="ForPrinting">
        <div class="StyleCostSheet">
            @Html.Partial("_StyleCreateEditPartial", Model)
            <div>
                @Html.Partial("_CostComponentsPartial", Model)
            </div>
        </div>
    </div>
}

OJewelry/Views/Styles/Sell.cshtml
@model OJewelry.Models.MemoViewModel

@{
    ViewBag.Title = "Sell";
}

<!--
    <h2>Sell <i>@Model.style.Name</i></h2> 
-->
<h2> Sell page under construction</h2>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.style.Id }) |
    @Html.ActionLink("Style List", "Index", new { CollectionId = ViewBag.CollectionID })
</p>

OJewelry/Views/Styles/_CostComponentLastCol.cshtml
@model OJewelry.Models.StyleViewModel
@using OJewelry.Models


@if (Model.SVMOp != SVMOperation.Print)
{
    if (Model.DelBtnPos == SVMDelButtonPos.Right)
    {
        <div class="row">
            <div style="float: right">
                <button type="button" class="btn btn-default" onclick="RemoveComponentRow('@Model.SVMCCType', @Model.i)">
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            </div>
        </div>
    }
}