OJewelry/Models/Presenter.cs
namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Presenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presenter()
        {
            Memos = new HashSet<Memo>();
            Contacts = new HashSet<Contact>();
        }

        public int Id { get; set; }

        [StringLength(50)]
        [Required]
        public string Name { get; set; }

        private string shortname;

        [StringLength(10)]
        public string ShortName
        {
            get
            {
                if (shortname == null || shortname.Trim() =="")
                {
                    if (Name == null) return "";
                    shortname = Name.PadRight(10).Substring(0, 3).ToUpper();
                    return Name.PadRight(10).Substring(0, 3).ToUpper();
                } else {
                    return shortname.Trim();
                }
            }
            set {
                if (value != null)
                {
                    shortname = value.PadRight(10).Substring(0, 3).ToUpper();
                }
            }
        }

        [StringLength(10)]
        public string Phone { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        public int CompanyId { get; set; }

        public virtual Company Company { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memo> Memos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}

OJewelry/Models/PresenterViewModel.cs
namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using static OJewelry.Classes.Validations;

    public enum PVCMState { Clean, Dirty, Added, Deleted, Unadded }

    [NotMapped]
    public class PresenterViewContactModel
    {
        public PresenterViewContactModel() { }
        public PresenterViewContactModel(Contact contact)
        {
            Id = contact.Id;
            Name = contact.Name;
            Phone = contact.Phone;
            Email = contact.Email;
            JobTitle = contact.JobTitle;
            State = PVCMState.Dirty;
            PresenterId = contact.PresenterId;
        }

        public Contact GetContact()
        {
            return new Contact(this);
        }

        public int Id { get; set; }
        [StringLength(50)]
        [Display(Name = "Name")]
        //[Required(ErrorMessage = "Name is required.")]
        [RequiredIfNotRemoved]
        public string Name { get; set; }

        [DisplayName("Phone")]
        [DataType(DataType.PhoneNumber)]
        [Phone]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string Phone { get; set; }

        [StringLength(50)]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [StringLength(50)]
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }

        public int? PresenterId { get; set; }


        public PVCMState State { get; set; }
    }
    public class PresenterViewModel
    {

        public PresenterViewModel()
        {
            Location = new Presenter();
            contacts = new List<PresenterViewContactModel>();
        }
        public string Phone { get; set; }
        public Presenter Location { get; set; }
        public List<PresenterViewContactModel> contacts { get; set; }

    }

    public partial class Contact
    {
        public Contact() { }
        public Contact(PresenterViewContactModel pvcm)
        {
            Id = pvcm.Id;
            Name = pvcm.Name;
            Phone = pvcm.Phone;
            Email = pvcm.Email;
            JobTitle = pvcm.JobTitle;
            PresenterId = pvcm.PresenterId;

            //CompanyId = pvcm.CompanyID;
        }

    }
}

OJewelry/Controllers/PresentersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml;
using OJewelry.Models;
using OJewelry.Classes;
using System.Text.RegularExpressions;

namespace OJewelry.Controllers
{
    [Authorize]
    public class PresentersController : Controller
    {
        private OJewelryDB db = new OJewelryDB();

        // GET: Presenters
        public ActionResult Index(int? companyId)
        {
            if (companyId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Company co = db.FindCompany(companyId);
            if (co == null)
            {
                return HttpNotFound();
            }
            var presenters = db.Presenters.Where(x => x.CompanyId == companyId).OrderBy(p=>p.Name).Include(p => p.Company);
            foreach (Presenter p in presenters)
            {
                p.Phone = SetFormattedPhone(p.Phone);
            }
            ViewBag.CompanyName = co.Name;
            ViewBag.CompanyId = co.Id;
            return View(presenters.ToList());
        }

        // GET: Presenters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Presenter presenter = db.Presenters.Find(id);
            presenter.Company = db.FindCompany(presenter.CompanyId);
            if (presenter == null)
            {
                return HttpNotFound();
            }
            return View(presenter);
        }

        // GET: Presenters/Create
        public ActionResult Create(int? companyId)
        {
            if (companyId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Company co = db.FindCompany(companyId);
            if (co == null)
            {
                return HttpNotFound();
            }
            PresenterViewModel pvm = new PresenterViewModel();
            ViewBag.CompanyName = co.Name;
            ViewBag.CompanyId = co.Id;
            pvm.Location.CompanyId = co.Id;
            return View(pvm);
        }

        // POST: Presenters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PresenterViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                pvm.Location.Phone = GetNormalizedPhone(pvm.Phone);
                db.Presenters.Add(pvm.Location);
                SavePresenters(pvm.Location.Id, pvm.contacts);
                db.SaveChanges();
                return RedirectToAction("Index", new { companyId = pvm.Location.CompanyId });
            }

            pvm.Location.Company = db.FindCompany(pvm.Location.CompanyId);
            ViewBag.CompanyName = pvm.Location.Name;
            return View(pvm);
        }

        // GET: Presenters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PresenterViewModel pvm = new PresenterViewModel();
            pvm.Location = db.Presenters.Find(id);
            if (pvm.Location == null)
            {
                return HttpNotFound();
            }
            pvm.Phone = SetFormattedPhone(pvm.Location.Phone);
            List<Contact> contacts = db.Contacts.Where(x => x.Location.Id == pvm.Location.Id).ToList();
            foreach (Contact c in contacts)
            {
                PresenterViewContactModel pvcm = new PresenterViewContactModel(c);
                pvcm.Phone = SetFormattedPhone(c.Phone);
                pvm.contacts.Add(pvcm);
            }
            pvm.Location.Company = db.FindCompany(pvm.Location.CompanyId);

            return View(pvm);
        }

        // POST: Presenters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PresenterViewModel pvm)
        {
            pvm.Location.Company = db.FindCompany(pvm.Location.CompanyId);
            if (ModelState.IsValid)
            {
                db.Entry(pvm.Location).State = EntityState.Modified;
                pvm.Location.Phone = GetNormalizedPhone(pvm.Phone);
                SavePresenters(pvm.Location.Id, pvm.contacts);
                db.SaveChanges();
                return RedirectToAction("Index", new { companyId = pvm.Location.CompanyId });
            }
            pvm.Location.Company = db.FindCompany(pvm.Location.CompanyId);
            return View(pvm);
        }

        // GET: Presenters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Presenter presenter = db.Presenters.Find(id);
            presenter.Company = db.FindCompany(presenter.CompanyId);
            if (presenter == null)
            {
                return HttpNotFound();
            }
            return View(presenter);
        }

        // POST: Presenters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Presenter presenter = db.Presenters.Find(id);
            // only allow delete if there is more than one presenter for this company
            if (db.Presenters.Where(p => p.CompanyId == presenter.CompanyId).Count() < 2)
            {
                ViewBag.Message = "This is the only location for this company so it cannot be removed";
                return View(presenter);
            }
            /*  
            foreach (Memo m in db.Memos.Where(mm => mm.PresenterID == id))
            {
            }
            */
            int numMemos = db.Memos.Where(mm => mm.PresenterID == id).Count();
            if (numMemos != 0)
            {
                ViewBag.Message = "There are items in this location; it cannot be deleted.";
                return View(presenter);
            }
            else
            {
                int coid = presenter.CompanyId;
                List<Contact> contacts = new List<Contact>();
                foreach (Contact c in db.Contacts.Where(c => c.PresenterId == id))
                {
                    contacts.Add(c);
                }
                db.Contacts.RemoveRange(contacts);
                db.Presenters.Remove(presenter);
                db.SaveChanges();
                return RedirectToAction("Index", new { companyId = coid });
            }
        }

        void SavePresenters(int presenterId, List<PresenterViewContactModel> contacts)
        {
            Contact con;
            foreach (PresenterViewContactModel p in contacts)
            {
                p.Phone = GetNormalizedPhone(p.Phone);
                if (p.Name != null)
                {
                    p.PresenterId = presenterId;
                    switch (p.State)
                    {
                        case PVCMState.Added:
                            db.Contacts.Add(p.GetContact());
                            break;
                        case PVCMState.Deleted:
                            con = p.GetContact();
                            db.Entry(con).State = EntityState.Deleted;
                            db.Contacts.Remove(con);
                            break;
                        case PVCMState.Dirty:
                            con = p.GetContact();
                            db.Entry(con).State = EntityState.Modified;
                            break;
                        case PVCMState.Unadded:
                        case PVCMState.Clean:
                        default:
                            break;
                    }
                }
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public FileResult ExportLocationReport(int CompanyId, string sCurrDate)
        {
            byte[] b;

            DateTime curr;
            sCurrDate = sCurrDate.Replace("'", "");
            if (!DateTime.TryParse(sCurrDate, out curr))
            {
                curr = DateTime.Now.ToLocalTime();
            }
            string currDate = $"{curr.ToShortDateString()} {curr.ToShortTimeString()}";


            DCTSOpenXML oxl = new DCTSOpenXML();
            
            using (MemoryStream memStream = new MemoryStream())
            {
                using (SpreadsheetDocument document = SpreadsheetDocument.Create(memStream, SpreadsheetDocumentType.Workbook))
                {

                    // Build Excel File
                    WorkbookPart workbookPart = document.AddWorkbookPart();
                    workbookPart.Workbook = new Workbook();

                    WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                    worksheetPart.Worksheet = new Worksheet(new SheetData());

                    Sheets sheets = document.WorkbookPart.Workbook.AppendChild(new DocumentFormat.OpenXml.Spreadsheet.Sheets());

                    // declare locals
                    Row row;
                    Cell cell;
                    string loc;
                    int rr;

OJewelry/Views/Presenters/Create.cshtml
@model OJewelry.Models.PresenterViewModel

@{
    ViewBag.Title = $"{ViewBag.CompanyName} - Create Location";
}

<h2>Create a Location for <i>@ViewBag.CompanyName</i></h2>


@using (Html.BeginForm("Create", "Presenters", FormMethod.Post, new { id = "LocationsForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Location.CompanyId)

        @Html.Partial("_PresenterCreateEditInputs", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Cancel", "Index", "Presenters", new { companyId = Model.Location.CompanyId }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", Model.Location.CompanyId)
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/RowManager.js")
    @Scripts.Render("~/Scripts/SetupContacts-Presenters.js")
    @Scripts.Render("~/Scripts/FormatPhone.js")
}

OJewelry/Views/Presenters/Delete.cshtml
@model OJewelry.Models.Presenter

@{
    ViewBag.Title = $"{Model.Name} - Delete";
}

<h2>Delete the the <i>@Model.Name</i> Location</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        @Html.ActionLink("Cancel", "Index", "Presenters", new { companyId = Model.CompanyId }, new { @class = "btn btn-default" })

    </div>

    <div>
        <p class="text-danger">@ViewBag.Message</p>
    </div>
    }
</div>
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", Model.CompanyId)
</p>

OJewelry/Views/Presenters/Details.cshtml
@model OJewelry.Models.Presenter

@{
    ViewBag.Title = "Details";
}

<h2>The <i>@Model.Company.Name</i> Location</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { @companyId = Model.CompanyId })
</p>

OJewelry/Views/Presenters/Edit.cshtml
@model OJewelry.Models.PresenterViewModel

@{
    ViewBag.Title = $"{Model.Location.Name} - Edit";
}

<h2>Edit the <i>@Model.Location.Name</i> Location</h2>

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies", null) |
    @Html.Partial("_CompanyNavPartial", Model.Location.CompanyId)
</p>

@using (Html.BeginForm("Edit", "Presenters", FormMethod.Post, new { id = "LocationsForm" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Location.CompanyId)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Location.Id)

        @Html.Partial("_PresenterCreateEditInputs", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Delete", "Delete", new { id = Model.Location.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Cancel", "Index", "Presenters", new { companyId = Model.Location.CompanyId }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>

}

<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies", null) |
    @Html.Partial("_CompanyNavPartial", Model.Location.CompanyId)
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/RowManager.js")
    @Scripts.Render("~/Scripts/SetupContacts-Presenters.js")
    @Scripts.Render("~/Scripts/FormatPhone.js")
}

OJewelry/Views/Presenters/Index.cshtml
@model IEnumerable<OJewelry.Models.Presenter>

@{
    ViewBag.Title = $"{ViewBag.CompanyName} - Locations";
}

<h2>Locations for <i>@ViewBag.CompanyName</i></h2>

<p>
    @Html.ActionLink("Create New Location", "Create", new { @companyId = ViewBag.CompanyId })
</p>
@{
    string jsCall = $"GetLocalTime({ViewBag.companyId}, '{Url.Action("ExportLocationReport")}')";
}
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", (int)ViewBag.companyId) |
    <a class="ExportLink" href="#" onclick="@jsCall">Export Locations to Excel</a>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p class="MainMenu">
    @Html.ActionLink("Companies", "Index", "Companies") |
    @Html.Partial("_CompanyNavPartial", (int)ViewBag.companyId) |
    <a class="ExportLink" href="#" onclick="@jsCall">Export Locations to Excel</a>
    }

    @section Scripts {
        @Scripts.Render("~/Scripts/GetLocalTime.js")
    }

OJewelry/Views/Presenters/_PresenterCreateEditInputs.cshtml
@model OJewelry.Models.PresenterViewModel
@using OJewelry.Models


<div class="form-group">
    @Html.LabelFor(model => model.Location.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Location.Name, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Location.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Location.ShortName, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", onblur = "FormatPhoneNumber(this)" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Location.Email, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Location.Email, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>


<div class="form-group">
    @Html.ValidationMessageFor(model => model.Location.Name, "", new { @class = "text-danger" })
    @Html.ValidationMessageFor(model => model.Location.ShortName, "", new { @class = "text-danger" })
    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    @Html.ValidationMessageFor(model => model.Location.Email, "", new { @class = "text-danger" })
</div>

@if (Model != null && Model.contacts != null)
{
    <h4>Contacts</h4>
    <div id="ContactsTableHeader" class="form-group">
        @Html.LabelFor(model => model.contacts[0].Name, htmlAttributes: new { @class = "control-label contorl-label-left col-md-3" })
        @Html.LabelFor(model => model.contacts[0].JobTitle, htmlAttributes: new { @class = "control-label contorl-label-left col-md-3" })
        @Html.LabelFor(model => model.contacts[0].Phone, htmlAttributes: new { @class = "control-label contorl-label-left col-md-3" })
        @Html.LabelFor(model => model.contacts[0].Email, htmlAttributes: new { @class = "control-label contorl-label-left col-md-3" })
    </div>
    <div id="ContactsTableData">
        @for (int i = 0; i < Model.contacts.Count; i++)
        {
            <div class="form-group ContactsTableRowContainer">
                @Html.HiddenFor(model => model.contacts[i].State, new { @class = "ContactsState" })
                <div class="row ContactsTableRowData">
                    @Html.HiddenFor(model => model.contacts[i].Id)
                    @Html.HiddenFor(model => model.contacts[i].PresenterId)
                    <div>
                        @Html.EditorFor(model => model.contacts[i].Name, new { htmlAttributes = new { @class = "form-control requiredifnotremoved col-md-3", data_val_required = "Client Name is required" } })
                    </div>
                    <div>
                        @Html.EditorFor(model => model.contacts[i].JobTitle, new { htmlAttributes = new { @class = "form-control col-md-3" } })
                    </div>
                    <div>
                        @Html.EditorFor(model => model.contacts[i].Phone, new { htmlAttributes = new { @class = "form-control col-md-3", onblur = "FormatPhoneNumber(this)" } })
                    </div>
                    <div>
                        @Html.EditorFor(model => model.contacts[i].Email, new { htmlAttributes = new { @class = "form-control col-md-3" } })
                    </div>
                </div>
                <div class="row ContactsTableRowValidation">
                    @Html.ValidationMessageFor(model => model.contacts[i].Name, "", new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.contacts[i].Phone, "", new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.contacts[i].Email, "", new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.contacts[i].JobTitle, "", new { @class = "text-danger" })
                </div>
            </div>
        }
    </div>
}